version: "3.5"
services:
  maddy:
    image: foxcpp/maddy:latest
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maddydata:/data
    environment:
        # REPLACE DOMAINS WITH YOURS
      - MADDY_HOSTNAME=mx.hawari.dev
      - MADDY_DOMAIN=hawari.dev
    depends_on:
      - certsync

  # Synchronize certificates from traefik/acme.json to maddy every 24 hours
  certsync:
    image: stedolan/jq
    entrypoint: |
      /bin/bash -c "
        mkdir /out/tls;
        touch /out/tls/fullchain.pem;
        touch /out/tls/privkey.pem;
        jq -r '.letsencrypt.Certificates[] | select(.domain.main==\"mx.hawari.dev\") | .certificate' /data/acme.json | base64 -d > /out/tls/fullchain.pem;
        jq -r '.letsencrypt.Certificates[] | select(.domain.main==\"mx.hawari.dev\") | .key' /data/acme.json | base64 -d > /out/tls/privkey.pem;
      "
    volumes:
      - coolify-traefik-letsencrypt:/data:ro
      - maddydata:/out

  # Hit /?admin for setup
  # Webmail
  rainloop:
    image: hardware/rainloop
    volumes:
      - rainloop-data:/rainloop/data

  restarter:
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["/bin/sh", "-c", "while true; do sleep 86400; docker restart maddy-email-certsync-1; done"]
    restart: unless-stopped

volumes:
  maddydata:
  rainloop-data:
  coolify-traefik-letsencrypt: # Wherever you store your acme.json file from traefik
    external: true
